### ISSUE TITLE
Test need

### ISSUE THREAD

**Issue by pavinthan** [developerdino/example-articles-api#1]
Hi Dean Tedesco,
 
you did a great job, my kindly request please write tests for the APIs because It's help to beginners like me.

Thanks

**Comment by developerdino** [comment]
Hi Pavinthan,

Thanks for your requested issue, and yes it would be great to write unit tests for this application, but due to my time constraints this may not occur anytime in the near future. I am however happy for you to fork this project and attempt to write some tests yourself and I can review and comment on them for you so that you are able to learn.

Cheers
Dean

**Comment by developerdino** [comment]
Hi Pavanthan, 

@pedro-stanaka was nice enough to provide a working example of feature and unit tests. Hopefully this makes sense.
